//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceEmployees")]
    public interface IServiceEmployees {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/AddEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/AddEmployeeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.FullTimeEmployee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.PartTimeEmployee))]
        void AddEmployee(Shared.Entities.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/AddEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(Shared.Entities.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/DeleteEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/DeleteEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/UpdateEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/UpdateEmployeeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.FullTimeEmployee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.PartTimeEmployee))]
        void UpdateEmployee(Shared.Entities.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/UpdateEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(Shared.Entities.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/GetAllEmployees", ReplyAction="http://tempuri.org/IServiceEmployees/GetAllEmployeesResponse")]
        Shared.Entities.Employee[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/GetAllEmployees", ReplyAction="http://tempuri.org/IServiceEmployees/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<Shared.Entities.Employee[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/GetEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/GetEmployeeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.FullTimeEmployee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Shared.Entities.PartTimeEmployee))]
        Shared.Entities.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/GetEmployee", ReplyAction="http://tempuri.org/IServiceEmployees/GetEmployeeResponse")]
        System.Threading.Tasks.Task<Shared.Entities.Employee> GetEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://tempuri.org/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
        double CalcPartTimeEmployeeSalary(int idEmployee, int hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://tempuri.org/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
        System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmployeesChannel : Pruebas.ServiceReference1.IServiceEmployees, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmployeesClient : System.ServiceModel.ClientBase<Pruebas.ServiceReference1.IServiceEmployees>, Pruebas.ServiceReference1.IServiceEmployees {
        
        public ServiceEmployeesClient() {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddEmployee(Shared.Entities.Employee emp) {
            base.Channel.AddEmployee(emp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(Shared.Entities.Employee emp) {
            return base.Channel.AddEmployeeAsync(emp);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void UpdateEmployee(Shared.Entities.Employee emp) {
            base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(Shared.Entities.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
        
        public Shared.Entities.Employee[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<Shared.Entities.Employee[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public Shared.Entities.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<Shared.Entities.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public double CalcPartTimeEmployeeSalary(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalary(idEmployee, hours);
        }
        
        public System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalaryAsync(idEmployee, hours);
        }
    }
}
